# Generated by Django 2.0.3 on 2018-04-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=375)),
                ('height', models.IntegerField(default=812)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('breakpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fides.Breakpoint')),
            ],
        ),
    ]
