# Generated by Django 2.0.3 on 2018-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fides', '0002_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
