# Generated by Django 2.0.3 on 2018-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fides', '0003_auto_20180410_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='breakpoint',
        ),
        migrations.AddField(
            model_name='project',
            name='breakpoint',
            field=models.ManyToManyField(to='fides.Breakpoint'),
        ),
    ]
