# Generated by Django 2.0.3 on 2018-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fides', '0004_auto_20180410_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codename',
            field=models.CharField(default='Lorem', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('U', 'Unscraped'), ('S', 'Scraped')], default='U', max_length=1),
        ),
    ]
