# Generated by Django 2.0.3 on 2018-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fides', '0008_auto_20180413_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wizard_step',
            field=models.CharField(choices=[('BSD', 'Basic Site Details'), ('NS', 'Not Scraped'), ('S', 'Scraped'), ('AP', 'Add Pages'), ('PVA', 'Pre-Visual Assesment'), ('BID', 'Building Initial Dataset')], default='BSD', max_length=10),
        ),
    ]
