# Generated by Django 2.0.3 on 2018-04-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fides', '0009_auto_20180413_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPagePrevisualAssesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.TextField()),
                ('js_code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='wizard_step',
            field=models.CharField(choices=[('BSD', 'Basic Site Details'), ('SS', 'Scraping Started'), ('S', 'Scraped'), ('AP', 'Add Pages'), ('PVA', 'Pre-Visual Assesment'), ('BID', 'Building Initial Dataset')], default='BSD', max_length=10),
        ),
        migrations.AddField(
            model_name='projectpageprevisualassesment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fides.Project'),
        ),
    ]
