# Generated by Django 2.0.3 on 2018-04-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fides', '0010_auto_20180413_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpageprevisualassesment',
            name='test_original',
            field=models.BooleanField(default=True),
        ),
    ]
